### ISSUE TITLE
create account

### ISSUE THREAD

**Issue by takehikotakehiko** [gianlucadelgobbo/avnode#111]
creating an account, you have to select from single and crew, but the text is the same colour of the background, so it is like invisible, and a request alert appear if you do not select nothing.

then a problem with birthday appear:
Ops... UserTemp validation failed: birthday: Cast to Date failed for value "Invalid Date" at path "birthday"<br/>

**Comment by gianlucadelgobbo** [comment]
https://github.com/gianlucadelgobbo/AVnode.net/issues/149
