### ISSUE TITLE
gallery past events

### ISSUE THREAD

**Issue by takehikotakehiko** [gianlucadelgobbo/avnode#113]
there is no more the gallery of past events with pictures, only videos.

**Comment by takehikotakehiko** [comment]
i found it https://avnode.net/galleries but there is not a link to this page from the title menu header

**Comment by takehikotakehiko** [comment]
but each gallery have all picture index, but each single picture is empty. there is only the picture as main of each gallery.

**Comment by gianlucadelgobbo** [comment]
LINK PLEASE (IN THE NEW REPO)
