### ISSUE TITLE
Javascripts

### ISSUE THREAD

**Issue by alappe** [gianlucadelgobbo/avnode#12]

**Comment by gianlucadelgobbo** [comment]
Client side fancy js

**Comment by stefanisak** [comment]
@alappe What was it about?

**Comment by alappe** [comment]
I don't remember exactly, I'd say about (re?)structuring the client js…

**Comment by stefanisak** [comment]
Ok, then it's way too generic. We should tackle those issues in separate tickets: #29, #42, #43. @alappe can you close it?

**Comment by gianlucadelgobbo** [comment]
Ok yes was client js

On Monday, 1 February 2016, Andreas Lappe <notifications@github.com> wrote:

> Closed #12 <https://github.com/gianlucadelgobbo/avnode/issues/12>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gianlucadelgobbo/avnode/issues/12#event-533869723>.
>


-- 

Gianluca
______________________________________
Flyer communication
www.flyer.it
Via del Verano 39 - 00185 Roma
Tel. +39 06 78147301 Fax +39 06 78390805
