### ISSUE TITLE
Use mongoose

### ISSUE THREAD

**Issue by alappe** [gianlucadelgobbo/avnode#18]
While I don't know the history of the project and the reasons for the decisions made, I think using [mongoose](https://www.npmjs.com/package/mongoose) might be good to have a little more abstraction of the models…

@gianlucadelgobbo Please feel free to say no if you thought about it before and decided against it…

**Comment by brucelane** [comment]
+1

**Comment by gianlucadelgobbo** [comment]
No I'm not against just never used

**Comment by alappe** [comment]
It's in there… While it hasn't fully replaced the old db structure yet, it will gradually…
