### ISSUE TITLE
no app/common/config.js file

### ISSUE THREAD

**Issue by ssm2017** [gianlucadelgobbo/avnode#2]
hello
the readme file is asking to configure the file located in app/common/config.js but the folder and the file do not exist.
a friend gave me an old example that i have put in app/server folder

**Comment by stefanisak** [comment]
We are using `getconfig`, so I guess this one is done. @gianlucadelgobbo can you close it?

**Comment by gianlucadelgobbo** [comment]
yes is ok if you are using it to manage all the query, if yes you can close
it


Gianluca
______________________________________
Flyer communication
www.flyer.it
Via del Verano 39 - 00185 Roma
Tel. +39 06 78147301 Fax +39 06 78390805
