### ISSUE TITLE
Add tests and travis…

### ISSUE THREAD

**Issue by alappe** [gianlucadelgobbo/avnode#20]
E.g. with 43bc37479 several modules are used but have not been added to the dependencies. Travis would catch that while running the application and report back…

**Comment by alappe** [comment]
As I have no access to the project settings, I cannot add travis as a service…

@gianlucadelgobbo you can have a look at it if you want… We need to find a way to set up a stubbed DB for the tests then…

**Comment by gianlucadelgobbo** [comment]
DONE, can you check?
