### ISSUE TITLE
missing dependencies in the doc

### ISSUE THREAD

**Issue by ssm2017** [gianlucadelgobbo/avnode#3]
hello
using a fresh install of node.js nodejs v0.10.33
when trying to run avnode, it is telling me that the following modules need to be installed : 
'express'
'bcrypt-nodejs'
'mongodb'
'request'
'imagemagick'
'mkdirp'
'moment'
'accounting'
'passport'
'passport-facebook'
'passport-twitter'
'passport-google-oauth'
'passport-local'
'i18n'
'stylus'

**Comment by stefanisak** [comment]
At the moment we don't have any missing dependency, especially not the described ones. So I guess this one is done. @gianlucadelgobbo can you close it?
