### ISSUE TITLE
Flxer API not working

### ISSUE THREAD

**Issue by stefanisak** [gianlucadelgobbo/avnode#32]
I guess one of those request is supposed to work:
```
Request: curl -X POST https://flxer.net/api/login -d '{"login": "", "password": "" }'
Response: {"login":false}

Request: curl -X POST https://flxer.net/api/login -d '{"login": "", "password": "" }' --header "Content-Type: application/json”
Response: {"login":false}
```
@gianlucadelgobbo
I tried it with the credentials you named and the password both plain text and bcrypted. Everything I could get is a ` {"login":false}` message. Am I missing something or can you please have a look at it?

**Comment by gianlucadelgobbo** [comment]
I tried with a form on a local page and it works:
    <form method="post" action="https://flxer.net/api/login">
    	<input type="text" name="login" value="GianlucaDelGobbo" />
    	<input type="password" name="password" value="...." />
    	<input type="submit" value="submit">
    </form>

**Comment by gianlucadelgobbo** [comment]
In this way too
```
curl -X POST https://flxer.net/api/login -d 'login=GianlucaDelGobbo&password=....'
```
