### ISSUE TITLE
No inlined JS for generic purposes

### ISSUE THREAD

**Issue by stefanisak** [gianlucadelgobbo/avnode#43]

**Comment by gianlucadelgobbo** [comment]
Ok

On Monday, 1 February 2016, Stefan Isak <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gianlucadelgobbo/avnode/issues/43>.
>


-- 

Gianluca
______________________________________
Flyer communication
www.flyer.it
Via del Verano 39 - 00185 Roma
Tel. +39 06 78147301 Fax +39 06 78390805
