### ISSUE TITLE
Controlpanel > user > public

### ISSUE THREAD

**Issue by stefanisak** [gianlucadelgobbo/avnode#45]
Still to do:
* Search and locate functionality for locations

@gianlucadelgobbo Please check if everything else is in place or if something is missing or broken.

**Comment by gianlucadelgobbo** [comment]
Profile url
Check not working

At least 1 City & Country is required, the other info are an optional, lat & long are generated but maybe we need a way to set up the point on a map

Maybe better to ask to @donostiastudio to make a final layout?

**Comment by stefanisak** [comment]
IMHO finished
