### ISSUE TITLE
Controlpanel > user > password

### ISSUE THREAD

**Issue by stefanisak** [gianlucadelgobbo/avnode#47]
TBD:
* Email required if password is changed?

@gianlucadelgobbo Please check if everything else is in place or if something is missing or broken.

**Comment by gianlucadelgobbo** [comment]
you mean email confirm? for sure


Gianluca
______________________________________
Flyer communication
www.flyer.it
Via del Verano 39 - 00185 Roma
Tel. +39 06 78147301 Fax +39 06 78390805

**Comment by stefanisak** [comment]
User gets notified if the password was changed.
