### ISSUE TITLE
Controlpanel > user > private

### ISSUE THREAD

**Issue by stefanisak** [gianlucadelgobbo/avnode#48]
Still to do:
* Little bug with the date format

@gianlucadelgobbo Please check if everything else is in place or if something is missing or broken.

**Comment by gianlucadelgobbo** [comment]
Country of citizenship
Maybe better to add multiple option
we need to add here the address for official residency?
ID/Passport number?

**Comment by stefanisak** [comment]
Please decide if you want to change properties as described above and if so reopen the ticket. To me those are edge cases and of lower priority.
