### ISSUE TITLE
Controlpanel > user > emails

### ISSUE THREAD

**Issue by stefanisak** [gianlucadelgobbo/avnode#49]
@gianlucadelgobbo Please check if everything is in place or if something is missing or broken.

**Comment by gianlucadelgobbo** [comment]
Is not working, when I clicked on the basket icon disabled on the first mail, my other 2 email was the same of the primary

Anyway we need to confirm to send email so lets start when an smtp is defined

**Comment by stefanisak** [comment]
Done
