### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by stefanisak** [gianlucadelgobbo/avnode#62]
Still to do:
* Move signup form to new structure

**Comment by gianlucadelgobbo** [comment]
Can't find the signup form
https://dev.avnode.net/signup ?
https://dev.avnode.net/controlpanel/signup ?
@donostiastudio we have to find a place where to put the invitation to register or login

**Comment by stefanisak** [comment]
I've rebuild the signup form. You'll find it here: https://dev.avnode.net/controlpanel/signup

Be aware that amazon is still running in sandbox mode, so signup will only work for whitelisted email address.
