### ISSUE TITLE
Localisations

### ISSUE THREAD

**Issue by stefanisak** [gianlucadelgobbo/avnode#63]
* One should add missing translations
* What about `app/public/_lang`? Where do these files come from and what are they supposed to do?

**Comment by gianlucadelgobbo** [comment]
Can you better explain?


Gianluca
______________________________________
Flyer communication
www.flyer.it
Via del Verano 39 - 00185 Roma
Tel. +39 06 78147301 Fax +39 06 78390805

**Comment by stefanisak** [comment]
I was wondering about the purpose of `/app/public/_lang`. What I see is a mixture of key values no one seems to access. So what to do with it?

**Comment by gianlucadelgobbo** [comment]
i think was for client side localization


Gianluca
______________________________________
Flyer communication
www.flyer.it
Via del Verano 39 - 00185 Roma
Tel. +39 06 78147301 Fax +39 06 78390805

**Comment by stefanisak** [comment]
*«Was»* means we can delete it?

**Comment by gianlucadelgobbo** [comment]
If we translate labels in another way in js clint side yes

On Monday, 1 February 2016, Stefan Isak <notifications@github.com> wrote:

> *«Was»* means we can delete it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gianlucadelgobbo/avnode/issues/63#issuecomment-178062119>
> .
>


-- 

Gianluca
______________________________________
Flyer communication
www.flyer.it
Via del Verano 39 - 00185 Roma
Tel. +39 06 78147301 Fax +39 06 78390805
